# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bT2Y-eI4ISPu26nnX9Mz1vFX8slpTNne
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

vocab_size=1000
embedding_dim=64
max_length=100

model=tf.keras.models.Sequential([
      Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_length),
      LSTM(64),
      Dense(1,activation='sigmoid')
])

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()